ppw_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('story5.urls')),
]

urlpatterns += staticfiles_urlpatterns()

story5/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'story5'
urlpatterns = [
    path('', views.home, name='home' ),
    path('tentang-diriku', views.tentang_diriku, name='about'),
    path('pengalaman', views.pengalaman, name="exp"),
    path('under-construction', views.under_construction, name="under"),
    path('jadwal', views.form_jadwal, name= 'jadwal'),
    path('jadwal-delete/<id>/', views.delete_jadwal, name = 'jadwal-delete')
]

core/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

class Jadwal(models.Model):
    tanggal = models.DateField()
    jam = models.TimeField()
    nama_kegiatan = models.CharField(max_length= 100)
    tempat_kegiatan = models.CharField(max_length= 100)
    kategori = models.CharField(max_length= 100)
    hari = models.CharField(max_length=10, default = 'Senin')

story5/forms.py
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class FormJadwal(forms.Form):
    kategori = forms.CharField(max_length= 100, required=True)
    nama_kegiatan = forms.CharField(max_length= 100, required=True)
    tanggal = forms.DateField(
        required=True, 
        widget=DateInput)
    jam = forms.TimeField(
        required = True,
        widget=TimeInput,)
    tempat_kegiatan = forms.CharField(max_length= 100, required=True)
    
    

core/views.py
from django.shortcuts import render

# Create your views here.

story5/views.py
from django.shortcuts import render, redirect
from .forms import FormJadwal
from .models import Jadwal

def home(request):
    return render(request, "home.html")

def tentang_diriku(request):
    return render(request, "tentang_diriku.html")

def pengalaman(request):
    return render(request, "pengalaman.html")

def under_construction(request):
    return render(request, "under_construction.html")

def form_jadwal(request):
    if request.method == "POST":
        form = FormJadwal(request.POST)
        if form.is_valid():
            nama_kegiatan = form.cleaned_data['nama_kegiatan']
            kategori = form.cleaned_data['kategori']
            tanggal = form.cleaned_data['tanggal']
            jam = form.cleaned_data['jam']
            tempat = form.cleaned_data['tempat_kegiatan']
            hari = None
            if tanggal.strftime("%A") == "Monday":
                hari = "Senin"
            elif tanggal.strftime("%A") == "Tuesday":
                hari = "Selasa"
            elif tanggal.strftime("%A") == "Wednesday":
                hari = "Rabu"
            elif tanggal.strftime("%A") == "Thursday":
                hari = "Kamis"
            elif tanggal.strftime("%A") == "Friday":
                hari = "Jumat"
            elif tanggal.strftime("%A") == "Saturday":
                hari = "Sabtu"
            elif tanggal.strftime("%A") == "Sunday":
                hari = "Minggu"

            jadwal = Jadwal(
                nama_kegiatan = nama_kegiatan,
                kategori = kategori,
                tanggal = tanggal,
                jam = jam,
                tempat_kegiatan = tempat,
                hari = hari)
            jadwal.save()
            Jadwal.objects.order_by('-tanggal')
        return redirect("story5:jadwal")
    else:
        form = FormJadwal()
        return render(request, "form_jadwal.html", {"form" : form, "list_jadwal": Jadwal.objects.all()})

def delete_jadwal(request, id):
    jadwal = Jadwal.objects.get(id=id)
    jadwal.delete()
    return redirect("story5:jadwal")

templates/form_jadwal.html
{% extends 'navbar.html' %}
{% load static from staticfiles %}
{% block content %}
    <div style="display: flex; padding-top: 70px; min-height: 100vh; justify-content: space-around">
        <div class="mb-2 mr-4">
            <form action="" method="post">
                {% csrf_token %}
                <table> 
                    {{ form.as_table }}
                </table>
                <div  class = "mt-2" style = "text-align: center">
                    <input type="submit" value="Tambah Jadwal">
                </div> 
            </form>
        </div>

        {% if list_jadwal.exists  %}   
        <div class="jadwal">
            <table border= "2">
                <tr>
                    <th>Kategori</th>
                    <th>Nama Kegiatan</th>
                    <th>Hari</th>
                    <th>Tanggal</th>
                    <th>Jam</th>
                    <th>Tempat</th>
                    <th>Delete</th>
                </tr>
            {% for jadwal in list_jadwal %}
                <tr>
                    <th>{{jadwal.kategori}}</th>
                    <th>{{jadwal.nama_kegiatan}}</th>
                    <th>{{jadwal.hari}}</th>
                    <th>{{jadwal.tanggal}}</th>
                    <th>{{jadwal.jam}}</th>
                    <th>{{jadwal.tempat_kegiatan}}</th>
                    <th>
                        <a href="{% url 'story5:jadwal-delete' id=jadwal.id %}"><button>delete</button></a>
                    </th>
                </tr>
            {% endfor %}
            </table>
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/home.html
{% extends 'navbar.html' %}
{% load static from staticfiles %}
{% block content %}
    <div class="hlmn-satu">
        <div class="nama">
            <div class="kotak"></div>
            <div class="title-name">
                <h1>Muhammad Rafif Elfazri</h1>
                <h2>Biografi Profesional</h2>
            </div>
        </div>
        
    </div>
{% endblock %}

    
    

templates/navbar.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'Story4.css' %}" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>My Web</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-rafif">
        <a class="navbar-brand" href="{% url 'story5:home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
            <a class="nav-item nav-link active " href="{% url 'story5:about' %}">Tentang Diriku</a>
            <a class="nav-item nav-link active " href="{% url 'story5:exp' %}">Pengalaman</a>
            <a class="nav-item nav-link active " href="{% url 'story5:jadwal' %}">Jadwal</a>
            <a class="nav-item nav-link active " href="#kontak">Kontak</a>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <div id="kontak" class="hlmn-kontak">
        <div class="title-all-hlmn">
                <h1>Kontak</h1>
        </div>
        <div class="kotak-hobi">
            <div class="icon-skill">
                <a href="https://www.instagram.com/rafifelfazri/?hl=id" target="_blank">
                    <img src="{% static 'Instagram.svg' %}"alt="" class="icon icon-media">
                </a>   
            </div>
            
            <div class="icon-skill">
                <a href="{% static 'm.rafif_elfazri.jpeg' %}" target="_blank">
                    <img src="{% static 'Line.svg' %}" alt="KDNKLNWKLN" class="icon icon-media">     
                </a>
            </div>
            <div class = "icon-skill">
                <a href="https://www.linkedin.com/in/rafif-elfazri-765634118" target="_blank">
                    <img src="{% static 'LinkedIn.svg' %}" alt="" class="icon icon-media">
                </a>
            </div>
            <div class = "icon-skill">
                <a href="https://wa.me/6282178150093" target="_blank">
                    <img src="{% static 'WhatsApp.svg' %}" alt="" class="icon icon-media">
                </a>    
            </div>  
        </div>
    </div>
</body>
</html>

templates/pengalaman.html
{% extends 'navbar.html' %}
{% load static from staticfiles %}
{% block content %}
    <div id= "pengalaman" class="hlmn-empat">
        <div class="title-all-hlmn">
                <h1>Pengalaman</h1>
        </div>
        <div class="kotak-hobi">
            <div class="icon-skill">
                <img src="{% static 'Logistic.svg' %}" alt="" class="icon ">
                <h6 class="icon-name">TOSKA UI<br>Logistic Staff (2019)</h6>
            </div>
            <div class="icon-skill">
                <img src="{% static 'SEA.svg' %}" class="icon">
                <h6 class="icon-name">Compfest Sofware Engineering<br>Academy Participant</h6>

            </div>
        </div>
        <div class="title-all-hlmn">
                <h1>Skill</h1>
        </div>
        <div class="kotak-hobi">
                <div class="icon-skill">
                    <img src="{% static 'Java.svg' %}" alt="" class="icon">
                    <h6 class="icon-name">Java</h6>
                </div>
                <div class="icon-skill">
                    <img src="{% static 'python.svg' %}" alt="" class="icon">
                    <h6 class="icon-name">Python</h6>
                </div>
                <div class ="icon-skill">
                    <img src="{% static 'JavaScript.svg' %}" alt="" class="icon">
                    <h6 class="icon-name">JavaScript</h6>
                </div> 
        </div>
    </div>
{% endblock %}

templates/tentang_diriku.html
{% extends 'navbar.html' %}
{% load static from staticfiles %}
{% block content %}
<div id ="about" class="hlmn-dua">
    <div class="title-hlmn-dua">
        <h1>Tentang Diriku</h1>
    </div>
    <div class="kotak-bio">
        <img src="{% static 'PP.jpeg' %}" alt="">
        <div class="bio-tulisan">
            <p>Nama<br>Muhammad Rafif Elfazri</p>
            <p>Tanggal Lahir<br>24 April 2000</p>
            <p>Asal<br>Palembang</p>
            <p>Universitas<br>Universitas Indonesia</p>
            <a class="link" href="{% url 'story5:under' %}"><p>More About Me...</p></a>
        </div>   
    </div>
</div>

<div class="hlmn-tiga">
        <div class="title-all-hlmn">
                <h1>Hobi</h1>
        </div>
        <div class="kotak-hobi">
            <div class="icon-skill">
                    <img src="{% static 'football.svg' %}" alt="" class="icon" style="transform: rotate(90deg)">
                    <h6 class="icon-name">Football</h6>
            </div>
            <div class="icon-skill">
                    <img src="{% static 'walk.svg' %}" alt="" class="icon">
                    <h6 class="icon-name">Jalan Kaki</h6>

            </div>
            <div class ="icon-skill">
                    <img src="{% static 'Youtube.svg' %}" alt="" class="icon">
                    <h6 class="icon-name">Menonton</h6>
            </div> 
        </div>
        <div class="title-all-hlmn">
                <h1>Deskripsi</h1>
        </div>
        <div class="text-align-center mr-auto ml-auto" style="width: 80%">
                <p class="deskripsi"> 
                        Saya adalah mahasiswa rantauan yang menimba ilmu di Universitas Indonesia.
                        Saya sangat tertarik dalam bidang programming dan <br>
                        saya ingin terus mempelajari hal baru dan tidak takut untuk mencobanya.
        </p>
        </div>
</div>
{% endblock %}

templates/under_construction.html
 {% extends 'navbar.html' %}
 {% load static from staticfiles %}
 {% block content %}   
    <div class = "hlmn-under">
        <div class="kotak-under">
            <h1 class>Under Construction</h1>
            <img class="photo-const" src="{% static 'myPhoto.png' %}" alt="DUarrr">
            <h1>Enjoy My Photo For Now!!!!</h1>
        </div> 
    </div>
{% endblock %}